### ISSUE TITLE
NO MQTT connection 

### ISSUE THREAD

**Issue by takebene** [FreddyFFM/shellyupdater#10]
I have the same problem with the MQTT connection. I tried it with and without password. I have not found any further information in the log files.
This is my docker-compose setup:

## docker-compose.yml
```yml 
version: '2'

services:
  shellyupdater:
    image: shellyupdater
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/home/updater/data
    environment:
      - DJANGO_SETTINGS_MODULE=shellyupdater.settings
      - RUN_ENV=DOCKER
    depends_on: 
      - mosquitto
    build: .
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    #network_mode: host
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
```

_Originally posted by @takebene in https://github.com/FreddyFFM/shellyupdater/issues/3#issuecomment-911894499_
