### ISSUE TITLE
No MQTT Connection available!

### ISSUE THREAD

**Issue by FlorianDessloch** [FreddyFFM/shellyupdater#3]
Hi,
I get "No MQTT Connection available!", no matter what I put into .env.
This is my mqtt section of .env:

# MQTT
MQTT_BROKER_ADDRESS='192.168.102.11:1883'
MQTT_USERNAME=''
MQTT_PASSWORD=''
MQTT_SHELLY_ANNOUNCE_TOPIC='shellies/announce'
MQTT_SHELLY_COMMAND_TOPIC='shellies/command'
MQTT_SHELLY_BASE_TOPIC='shellies/'

I tried it witout the port, without th quotation marks, no change.
I do not use authentication, so I left that alone.
Any idea?

**Comment by FreddyFFM** [comment]
Currently Username and Password are mandatory. I will plan mqtt without authentication for the next releases

**Comment by takebene** [comment]
I have the same problem with the MQTT connection. I tried it with and without password. I have not found any further information in the log files.
This is my docker-compose setup:

## docker-compose.yml
```yml 
version: '2'

services:
  shellyupdater:
    image: shellyupdater
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/home/updater/data
    environment:
      - DJANGO_SETTINGS_MODULE=shellyupdater.settings
      - RUN_ENV=DOCKER
    depends_on: 
      - mosquitto
    build: .
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    #network_mode: host
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
```
